# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Myspace
version:      0.10
version_from: lib/WWW/Myspace.pm
installdirs:  site
requires:
    HTTP::Request::Form:           0
    Spiffy:                        0.24
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
