--- #YAML:1.0
name:                WWW-Myspace
version:             0.88
abstract:            Access MySpace.com profile information from Perl
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Config::General:               0
    Contextual::Return:            0
    Crypt::SSLeay:                 0.53
    File::Spec::Functions:         0
    Locale::SubCountry:            1.38
    Params::Validate:              0
    Spiffy:                        0.24
    Test::More:                    0
    Time::ParseDate:               100.010301
    URI::Escape:                   0
    WWW::Mechanize:                1.2
    YAML:                          0.39
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Grant Grueninger <grantg@cpan.org>
