# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Myspace
version:      0.68
version_from: lib/WWW/Myspace.pm
installdirs:  site
requires:
    Config::General:               0
    Contextual::Return:            0
    Crypt::SSLeay:                 0.53
    File::Spec::Functions:         0
    Locale::SubCountry:            1.38
    Params::Validate:              0
    Spiffy:                        0.24
    Test::More:                    0
    Time::Local:                   0
    WWW::Mechanize:                1.2
    YAML:                          0.39

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
