#!/usr/bin/perl -w -I../lib
# This script is here for testing.  browse method doesn't work yet.

use WWW::Myspace;

my $myspace = new WWW::Myspace;

my @friends = $myspace->browse( {} );

print "Found " . @friends . " friends\n";

foreach my $id ( @friends ) {
	print $id . "\n";
}
