#!/usr/bin/perl -w -I../lib

use WWW::Myspace;

my $myspace = new WWW::Myspace;
unless ( $myspace->logged_in ) { die "Login failed\n" }

my @friends;

if ( @ARGV ) {
  @friends = $myspace->friends_from_profile( @ARGV );
} else {
  @friends = $myspace->get_friends;
}

print "Got " . @friends . " friends:\n";

foreach ( @friends ) {
	print;
	print "\n";
}
