#!/usr/bin/perl -w -I../lib

use WWW::Myspace;
use CGI qw/:standard/;;
my $myspace = new WWW::Myspace;

# Display a login form
print header,
    start_html('Is it worth logging in?'),
    $myspace->get_login_form,
    end_html;

